### ISSUE TITLE
Can not execute Test Run in JUnit 5

### ISSUE THREAD

**Issue by ntthaibk** [qase-tms/qase-java#122]
I've followed the instruction in the Junit 5 integration repo, with the pom configured exactly like described. But then got this error where no test case run.

I've put the tag @QaseId(Test case Code) under @Test annotation like guided

WARNING: TestExecutionListener [io.qase.junit5.QaseExtension] threw exception for method: testPlanExecutionFinished(org.junit.platform.launcher.TestPlan@7fdd43cd)
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) [Guice/ErrorInCustomProvider]: IllegalStateException: QaseException: 
  at QaseModule.apiClient(QaseModule.java:28)
      \_ installed by: Modules$OverrideModule -> Modules$CombinedModule -> QaseModule
  at QaseModule.runsApi(QaseModule.java:42)
      \_ for 1st parameter
  at QaseModule.runsApi(QaseModule.java:42)
      \_ installed by: Modules$OverrideModule -> Modules$CombinedModule -> QaseModule
  at QaseTestCaseListenerImpl.<init>(QaseTestCaseListenerImpl.java:19)
      \_ for 1st parameter
  while locating QaseTestCaseListenerImpl
  while locating QaseTestCaseListener

Learn more:
  https://github.com/google/guice/wiki/ERROR_IN_CUSTOM_PROVIDER

1 error

======================
Full classname legend:
======================
Modules$CombinedModule:   "com.google.inject.util.Modules$CombinedModule"
Modules$OverrideModule:   "com.google.inject.util.Modules$OverrideModule"
QaseException:            "io.qase.api.exceptions.QaseException"
QaseModule:               "io.qase.guice.module.QaseModule"
QaseTestCaseListener:     "io.qase.api.services.QaseTestCaseListener"
QaseTestCaseListenerImpl: "io.qase.api.services.impl.QaseTestCaseListenerImpl"
========================
End of classname legend:
========================

        at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:251)
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1104)
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1139)
        at io.qase.junit5.QaseExtension.createQaseListener(QaseExtension.java:113)
        at io.qase.junit5.QaseExtension.getQaseTestCaseListener(QaseExtension.java:36)
        at io.qase.junit5.QaseExtension.testPlanExecutionFinished(QaseExtension.java:68)
        at org.junit.platform.launcher.core.CompositeTestExecutionListener.lambda$testPlanExecutionFinished$14(CompositeTestExecutionListener.java:81)
        at org.junit.platform.launcher.core.CompositeTestExecutionListener.lambda$notifyEach$19(CompositeTestExecutionListener.java:95)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.junit.platform.launcher.core.CompositeTestExecutionListener.notifyEach(CompositeTestExecutionListener.java:93)
        at org.junit.platform.launcher.core.CompositeTestExecutionListener.testPlanExecutionFinished(CompositeTestExecutionListener.java:81)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:91)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
        at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
        at org.apache.maven.surefire.junitplatform.LazyLauncher.execute(LazyLauncher.java:55)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:223)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:175)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:139)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
        at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
Caused by: java.lang.IllegalStateException: io.qase.api.exceptions.QaseException: 
        at io.qase.api.QaseClient.initApiClient(QaseClient.java:52)
        at io.qase.api.QaseClient.getApiClient(QaseClient.java:67)
        at io.qase.guice.module.QaseModule.apiClient(QaseModule.java:28)
        at io.qase.guice.module.QaseModule$$FastClassByGuice$$500400.GUICE$TRAMPOLINE(<generated>)
        at io.qase.guice.module.QaseModule$$FastClassByGuice$$500400.apply(<generated>)
        at com.google.inject.internal.ProviderMethod$FastClassProviderMethod.doProvision(ProviderMethod.java:260)
        at com.google.inject.internal.ProviderMethod.doProvision(ProviderMethod.java:171)
        at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.provision(InternalProviderInstanceBindingImpl.java:185)
        at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.get(InternalProviderInstanceBindingImpl.java:162)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:40)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:60)
        at com.google.inject.internal.ProviderMethod.doProvision(ProviderMethod.java:171)
        at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.provision(InternalProviderInstanceBindingImpl.java:185)
        at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.get(InternalProviderInstanceBindingImpl.java:162)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:40)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:60)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300)
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:60)
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1101)
        ... 24 more
Caused by: io.qase.api.exceptions.QaseException: 
        at io.qase.client.ApiClient.handleResponse(ApiClient.java:1070)
        at io.qase.client.ApiClient.execute(ApiClient.java:983)
        at io.qase.client.api.RunsApi.createRunWithHttpInfo(RunsApi.java:348)
        at io.qase.client.api.RunsApi.createRun(RunsApi.java:322)
        at io.qase.api.QaseClient.initApiClient(QaseClient.java:45)
        ... 50 more

**Comment by savkk** [comment]
Looks like some parameters are missing

could you add the following code to the before fixture:

QaseClient.getApiClient().setDebugging(true);

**Comment by ntthaibk** [comment]
even after set debugging to true, the log is still not emitted.

but when I remove and re-add lombok from maven, things got reéolved. Seems like a lombok problem. we can close it
