### ISSUE TITLE
DateTimeParseException when calling PlansApi.getplan

### ISSUE THREAD

**Issue by franke0739** [qase-tms/qase-java#33]
Sample of the code:

```
qaseApi = Configuration.getDefaultApiClient();
qaseApi.setApiKey(apiToken);
plansApi = new PlansApi(qaseApi);

plansApi.getPlan("xxx", 1)
```
Error:
`java.time.format.DateTimeParseException: Text '2022-02-03 11:49:16' could not be parsed at index 10
	at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1949)
	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1851)
	at java.time.LocalDateTime.parse(LocalDateTime.java:492)
	at io.qase.client.JSON.lambda$new$0(JSON.java:80)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at io.qase.client.JSON.deserialize(JSON.java:139)
	at io.qase.client.ApiClient.deserialize(ApiClient.java:795)
	at io.qase.client.ApiClient.handleResponse(ApiClient.java:1001)
	at io.qase.client.ApiClient.execute(ApiClient.java:925)
	at io.qase.client.api.PlansApi.getPlanWithHttpInfo(PlansApi.java:387)
	at io.qase.client.api.PlansApi.getPlan(PlansApi.java:367)`

**Comment by franke0739** [comment]
Thanks for the quick fix
