### ISSUE TITLE
Test suite execution crashed with exception after upgrading from 2.1.5 to 2.2.0

### ISSUE THREAD

**Issue by mikamikaWolt** [qase-tms/qase-java#71]
Qase library for TestNg and Java projects crashed with exception when performing the first test step (method with` io.qase.api.annotation.Step`), even if Qase is not enabled for this test run. The previous test commands command was done correctly.
With Qase enabled, a test run is not created on Qase "Tets runs" dashboard.

Log from the Maven suite:
```
[ERROR] Could not initialize class io.qase.configuration.QaseModule
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
[ERROR] Could not initialize class io.qase.configuration.QaseModule
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:656)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:282)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:245)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1183)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1011)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:857)
[ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:301)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:211)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:165)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:157)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:121)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:127)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:294)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:960)
[ERROR] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
[ERROR] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
```

Full log form sure fire report:
```
java.lang.NoSuchMethodError: 'java.util.concurrent.ConcurrentMap com.google.common.collect.MapMaker.makeComputingMap(com.google.common.base.Function)'
	at com.google.inject.internal.Annotations$AnnotationChecker.<init>(Annotations.java:104)
	at com.google.inject.internal.Annotations.<clinit>(Annotations.java:122)
	at com.google.inject.internal.ProviderMethodsModule.getKey(ProviderMethodsModule.java:131)
	at com.google.inject.internal.ProviderMethodsModule.createProviderMethod(ProviderMethodsModule.java:102)
	at com.google.inject.internal.ProviderMethodsModule.getProviderMethods(ProviderMethodsModule.java:85)
	at com.google.inject.internal.ProviderMethodsModule.configure(ProviderMethodsModule.java:75)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:229)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:238)
	at com.google.inject.spi.Elements.getElements(Elements.java:103)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:136)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
	at com.google.inject.Guice.createInjector(Guice.java:94)
	at com.google.inject.Guice.createInjector(Guice.java:71)
	at com.google.inject.Guice.createInjector(Guice.java:61)
	at io.qase.configuration.QaseModule.<clinit>(QaseModule.java:17)
	at io.qase.testng.QaseListener.getQaseTestCaseListener(QaseListener.java:28)
	at io.qase.testng.QaseListener.onTestStart(QaseListener.java:37)
	at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:73)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1389)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:559)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```

**Comment by mikamikaWolt** [comment]
JDK: 15.0.2 (https://www.oracle.com/java/technologies/javase/jdk15-archive-downloads.html) - Have to use lower version because of (https://stackoverflow.com/questions/67020698/appium-getting-a-java-lang-runtimeexception-java-lang-nosuchmethodexception)

Maven: 3.8.5

Running test from the command line with TestNG suite like: mvn -DsuiteNametest.xml test

**Comment by mbirintsev** [comment]
@mikamikaWolt 

I made a lot of effort to reproduce the behavior you reported. I changed the versions of the tools to speied by you and played around with their combinations but still, I have all tests passed successfully.

I suppose you utilize an external project to test the library (at least because there is no _suiteNametest.xml_ in the repository). 

From the stack trace, we can conclude Guice version conflict happens during the (test!) runtime.
To have the issue resolved I would suggest applying [this](https://stackoverflow.com/a/7176095) solution. I am not 100% sure it will resolve this very specific case, but the question itself is similar to this issue.

So, could you please either:

- share the test project with me
- or specify the dependency version (that must be `com.google.inject:guice:5.1.0`) by yourself in the `<dependencyManagement>` section?

Thank you in advance!

PS: There must be a mistyping in the `maven-surefire-plugin` version. [The central repository](https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-surefire-plugin) does not have `2.2.2` version, but instead `2.22.2` is present. So, I used that one.

**Comment by mikamikaWolt** [comment]
Of course, i have 2.22.2 version of maven-surefire-plugin

Sorry, i don't know which repository you are talking about, and why it has no suite.xml file... And I can't share my project with the public (Company confidential).

But I run test with TestNG suites, like mvn -DsuiteName=test.xml test.
All work with **qase-testng 2.1.5**, but **2.2.0** causes that `Could not initialize class io.qase.configuration.QaseModule` exception

Here is pom.xml (very close to the real one, and it has same issue)

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.wolt.autoqa</groupId>
    <artifactId>WoltAutoQA</artifactId>
    <version>1.3</version>

    <properties>
        <aspectj.version>1.9.9.1</aspectj.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <!-- Default Test Suite files if not being specified from mvn command line -->
        <suiteName>suites/emptySuite.xml</suiteName>
        <env>dev</env>
        <deviceName>ipad_sim_15</deviceName>
        <maven.build.timestamp.format>yyyy-MM-dd HH-mm-ss z</maven.build.timestamp.format>
        <timestamp>${maven.build.timestamp}</timestamp>
        <kotlin.version>1.7.10</kotlin.version>
        <detekt.version>1.21.0.1</detekt.version>
        <kotlin.compiler.incremental>true</kotlin.compiler.incremental>
    </properties>

    <build>
        <outputDirectory>/tmp/logs</outputDirectory>
        <resources>
            <resource>
                <directory>src/test/kotlin/resources</directory>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.22.2</version>
                <configuration>
                    <suiteXmlFiles>
                        <suiteName>${suiteName}</suiteName>
                    </suiteXmlFiles>
                    <testFailureIgnore>false</testFailureIgnore>
                    <argLine>
                        -javaagent:"${settings.localRepository}/org/aspectj/aspectjweaver/${aspectj.version}/aspectjweaver-${aspectj.version}.jar"
                    </argLine>
                    <systemPropertyVariables>
                        <env>${env}</env>
                        <deviceName>${deviceName}</deviceName>
                    </systemPropertyVariables>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.aspectj</groupId>
                        <artifactId>aspectjweaver</artifactId>
                        <version>${aspectj.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
            <plugin>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-maven-plugin</artifactId>
                <version>${kotlin.version}</version>
                <executions>
                    <execution>
                        <id>compile</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>test-compile</id>
                        <phase>test-compile</phase>
                        <goals>
                            <goal>test-compile</goal>
                        </goals>
                        <configuration>
                            <sourceDirs>
                                <sourceDir>${project.basedir}/src/test/kotlin</sourceDir>
                            </sourceDirs>
                        </configuration>
                    </execution>
                </executions>
                <configuration>
                    <jvmTarget>15</jvmTarget>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.10.1</version>
                <executions>
                    <execution>
                        <id>compile</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>testCompile</id>
                        <phase>test-compile</phase>
                        <goals>
                            <goal>testCompile</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <release>11</release>
                </configuration>
            </plugin>
            <plugin>
                <groupId>com.github.ozsie</groupId>
                <artifactId>detekt-maven-plugin</artifactId>
                <version>${detekt.version}</version>
                <configuration>
                    <report>
                        <report>txt:reports/detekt.txt</report>
                        <report>xml:reports/detekt.xml</report>
                    </report>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <dependencyManagement>
        <dependencies>
            <!-- https://mvnrepository.com/artifact/com.google.inject/guice -->
            <dependency>
                <groupId>com.google.inject</groupId>
                <artifactId>guice</artifactId>
                <version>5.1.0</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>

        <!-- https://github.com/Ozsie/detekt-maven-plugin -->
        <dependency>
            <groupId>com.github.ozsie</groupId>
            <artifactId>detekt-maven-plugin</artifactId>
            <version>${detekt.version}</version>
            <type>maven-plugin</type>
        </dependency>

        <!-- https://mvnrepository.com/artifact/org.slf4j/slf4j-simple -->
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>1.7.36</version>
            <scope>test</scope>
        </dependency>

        <!-- https://mvnrepository.com/artifact/io.appium/java-client -->
        <dependency>
            <groupId>io.appium</groupId>
            <artifactId>java-client</artifactId>
            <version>7.6.0</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/org.testng/testng -->
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>6.14.3</version>
            <scope>test</scope>
        </dependency>

        <!-- https://mvnrepository.com/artifact/org.json/json -->
        <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <version>20220320</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/com.googlecode.json-simple/json-simple -->
        <dependency>
            <groupId>com.googlecode.json-simple</groupId>
            <artifactId>json-simple</artifactId>
            <version>1.1.1</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-stdlib-jdk8 -->
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib-jdk8</artifactId>
            <version>${kotlin.version}</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-test -->
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-test-junit</artifactId>
            <version>${kotlin.version}</version>
            <scope>test</scope>
        </dependency>

        <!-- https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-maven-plugin -->
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-maven-plugin</artifactId>
            <version>${kotlin.version}</version>
            <scope>provided</scope>
        </dependency>

        <!-- https://mvnrepository.com/artifact/com.squareup.okhttp3/okhttp -->
        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
            <version>4.9.3</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/com.mailslurp/mailslurp-client-kotlin -->
        <dependency>
            <groupId>com.mailslurp</groupId>
            <artifactId>mailslurp-client-kotlin</artifactId>
            <version>12.5.0</version>
        </dependency>

        <!--  https://mvnrepository.com/artifact/com.fasterxml.jackson.module/jackson-module-kotlin/2.13.2-->
        <dependency>
            <groupId>com.fasterxml.jackson.module</groupId>
            <artifactId>jackson-module-kotlin</artifactId>
            <version>2.13.3</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/com.squareup.okhttp3/logging-interceptor -->
        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>logging-interceptor</artifactId>
            <version>4.9.3</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/io.qase/qase-testng -->
        <dependency>
            <groupId>io.qase</groupId>
            <artifactId>qase-testng</artifactId>
            <version>2.2.0</version>
            <scope>test</scope>
        </dependency>

        <!-- https://mvnrepository.com/artifact/io.github.cdimascio/dotenv-kotlin -->
        <dependency>
            <groupId>io.github.cdimascio</groupId>
            <artifactId>dotenv-kotlin</artifactId>
            <version>6.3.1</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/com.sksamuel.hoplite/hoplite-core -->
        <dependency>
            <groupId>com.sksamuel.hoplite</groupId>
            <artifactId>hoplite-core</artifactId>
            <version>2.3.0</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/com.sksamuel.hoplite/hoplite-yaml -->
        <dependency>
            <groupId>com.sksamuel.hoplite</groupId>
            <artifactId>hoplite-yaml</artifactId>
            <version>2.3.0</version>
            <scope>runtime</scope>
        </dependency>

    </dependencies>

</project>
```

**Comment by mbirintsev** [comment]
Gotcha! I reproduced it :)

**Comment by mbirintsev** [comment]
Well, I did it. The tests are passed well. 

# Short answer

## Option 1

Either, add
```
<dependency>
    <groupId>com.google.inject</groupId>
    <artifactId>guice</artifactId>
    <version>5.1.0</version>
    <scope>test</scope>
</dependency>
```
directly to `<dependencies>` 

## Option 2

or remove the dependency on

```
<dependency>
    <groupId>org.jetbrains.kotlin</groupId>
    <artifactId>kotlin-maven-plugin</artifactId>
    <version>${kotlin.version}</version>
    <scope>provided</scope>
</dependency>
```

# Long answer

Sorry, I do not know the specific of your particular testing project hence can not give any strong recommendations. 

The one thing I am sure about there is a namespace conflict. `kotlin-maven-plugin` has a transitive dependency on `org.sonatype.sisu:sisu-guava:jar:0.9.9`. Unfortunately, the lib seems to be a modification of the original Guava library. Taking into account that Guava includes Guice and Qase-for-Java is using Guice, this quite unobvious fail happens.

Feel free to reply or ask questions if you have any concern. 

Thank you, @mikamikaWolt !

PS: And yes, the namespace (aka package) from `org.sonatype.sisu:sisu-guava:jar:0.9.9` was winning that challenge, which caused the tests failing.

PPS: You can utilize `mvn dependency:tree` to investigate the dependencies by yourself. A good addition to that would be global search by `com.google.common.collect.MapMaker` in your IDE.

**Comment by mikamikaWolt** [comment]
Option 1
Adding Guice breaks the project. My project has automated tests with Selenium/Appium.

Code 
```
var driver: WebDriver (some initialisation here)
val wait = WebDriverWait(driver, 10)
wait.until(ExpectedConditions.alertIsPresent())
```
Compilation throws error on the 4rd line
`Type mismatch: inferred type is ExpectedCondition<Alert!>! but Function<in WebDriver!, TypeVariable(V)!>! was expected`

Option 2:
My project is written on Kotlin, so i can't remove kotlin-maven-plugin as it compiles the code.

**Comment by mbirintsev** [comment]
@mikamikaWolt ,

## Regarding Option 1

Sorry, but I can not conclude anything from the details provided.

The only guess is your libraries depend (possibly transitive) on the exact version of Guava or Guice. I would rather you find the required one among your dependencies of the corporate project.

## Regarding Option 2

Could you please clarify why the project requires having `kotlin-maven-plugin` specified **both** in `plugins` and `dependencies` sections?

Thank you!

**Comment by mikamikaWolt** [comment]
I have updated some libs in my pom.xml to the latest versions available:
com.sksamuel.hoplite
slf4j-simple
com.fasterxml.jackson.module version

and removed duplicated kotlin-maven-plugin import from dependencies.

This did the trick - all is working with 2.2.0 version.

Thank you for your time and help! Although it hasn't helped directly, it took me some nice ideas!
