### ISSUE TITLE
Getting 'java.lang.IllegalStateException' on getting test case by id

### ISSUE THREAD

**Issue by laurajunga** [qase-tms/qase-java#92]
Happens only with test cases that have parameters.

`new CasesApi(qaseApi).getCase(projectCode, testCaseId).getResult().getParams();`

When I'm trying to get same test case at https://developers.qase.io/reference/get-case everything works fine. 

Stacktrace:
`com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at path $.params
    	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
    	at com.google.gson.TypeAdapter.fromJsonTree(TypeAdapter.java:285)
    	at io.qase.client.model.TestCase$CustomTypeAdapterFactory$1.read(TestCase.java:1024)
    	at io.qase.client.model.TestCase$CustomTypeAdapterFactory$1.read(TestCase.java:1014)
    	at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199)
    	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
    	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
    	at com.google.gson.TypeAdapter.fromJsonTree(TypeAdapter.java:285)
    	at io.qase.client.model.TestCaseResponse$CustomTypeAdapterFactory$1.read(TestCaseResponse.java:165)
    	at io.qase.client.model.TestCaseResponse$CustomTypeAdapterFactory$1.read(TestCaseResponse.java:155)
    	at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199)
    	at com.google.gson.Gson.fromJson(Gson.java:932)
    	at com.google.gson.Gson.fromJson(Gson.java:897)
    	at com.google.gson.Gson.fromJson(Gson.java:846)
    	at io.qase.client.JSON.deserialize(JSON.java:292)
    	at io.qase.client.ApiClient.deserialize(ApiClient.java:849)
    	at io.qase.client.ApiClient.handleResponse(ApiClient.java:1059)
    	at io.qase.client.ApiClient.execute(ApiClient.java:983)
    	at io.qase.client.api.CasesApi.getCaseWithHttpInfo(CasesApi.java:505)
    	at io.qase.client.api.CasesApi.getCase(CasesApi.java:479)
    	at cloud.aranet.helpers.Qase.saveTestCaseResult(Qase.java:44)
    	at cloud.aranet.helpers.Hooks.cleanup(Hooks.java:18)
    Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at path $.params
    	at com.google.gson.internal.bind.JsonTreeReader.expect(JsonTreeReader.java:163)
    	at com.google.gson.internal.bind.JsonTreeReader.beginArray(JsonTreeReader.java:72)
    	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:80)
    	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
    	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
    	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
    	at com.google.gson.TypeAdapter.fromJsonTree(TypeAdapter.java:285)
    	at io.qase.client.model.TestCase$CustomTypeAdapterFactory$1.read(TestCase.java:1024)
    	at io.qase.client.model.TestCase$CustomTypeAdapterFactory$1.read(TestCase.java:1014)
    	at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199)
    	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
    	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
    	at com.google.gson.TypeAdapter.fromJsonTree(TypeAdapter.java:285)
    	at io.qase.client.model.TestCaseResponse$CustomTypeAdapterFactory$1.read(TestCaseResponse.java:165)
    	at io.qase.client.model.TestCaseResponse$CustomTypeAdapterFactory$1.read(TestCaseResponse.java:155)
    	at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199)
    	at com.google.gson.Gson.fromJson(Gson.java:932)
    	at com.google.gson.Gson.fromJson(Gson.java:897)
    	at com.google.gson.Gson.fromJson(Gson.java:846)
    	at io.qase.client.JSON.deserialize(JSON.java:292)
    	at io.qase.client.ApiClient.deserialize(ApiClient.java:849)
    	at io.qase.client.ApiClient.handleResponse(ApiClient.java:1059)
    	at io.qase.client.ApiClient.execute(ApiClient.java:983)
    	at io.qase.client.api.CasesApi.getCaseWithHttpInfo(CasesApi.java:505)
    	at io.qase.client.api.CasesApi.getCase(CasesApi.java:479)
    	at cloud.aranet.helpers.Qase.saveTestCaseResult(Qase.java:44)
    	at cloud.aranet.helpers.Hooks.cleanup(Hooks.java:18)
    	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    	at io.cucumber.java.Invoker.doInvoke(Invoker.java:66)
    	at io.cucumber.java.Invoker.invoke(Invoker.java:24)
    	at io.cucumber.java.AbstractGlueDefinition.invokeMethod(AbstractGlueDefinition.java:47)
    	at io.cucumber.java.JavaHookDefinition.execute(JavaHookDefinition.java:59)
    	at io.cucumber.core.runner.CoreHookDefinition.execute(CoreHookDefinition.java:46)
    	at io.cucumber.core.runner.HookDefinitionMatch.runStep(HookDefinitionMatch.java:21)
    	at io.cucumber.core.runner.ExecutionMode$1.execute(ExecutionMode.java:10)
    	at io.cucumber.core.runner.TestStep.executeStep(TestStep.java:92)
    	at io.cucumber.core.runner.TestStep.run(TestStep.java:64)
    	at io.cucumber.core.runner.TestCase.run(TestCase.java:110)
    	at io.cucumber.core.runner.Runner.runPickle(Runner.java:71)
    	at io.cucumber.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:151)
    	at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:135)
    	at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:27)
    	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
    	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
    	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
    	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
    	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
    	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
    	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
    	at io.cucumber.junit.Cucumber.runChild(Cucumber.java:199)
    	at io.cucumber.junit.Cucumber.runChild(Cucumber.java:90)
    	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
    	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
    	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
    	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
    	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
    	at io.cucumber.junit.Cucumber$RunCucumber.evaluate(Cucumber.java:234)
    	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
    	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
    	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
    	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
    	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
    	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
    	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
    	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
    	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
    	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
    	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
    	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:119)
    	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
    	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
    	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
    	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
    	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
    	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
    	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
    	at java.base/java.lang.Thread.run(Thread.java:834)`

**Comment by savkk** [comment]
fixed in 3.0.4
